In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm
import seaborn as sns
from sklearn.linear_model import LinearRegression

In [2]:
data = pd.read_csv('1.02. Multiple linear regression.csv')

In [3]:
data.head()

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

In [4]:
data.describe()

SAT  Rand 1,2,3        GPA
count    84.000000   84.000000  84.000000
mean   1845.273810    2.059524   3.330238
std     104.530661    0.855192   0.271617
min    1634.000000    1.000000   2.400000
25%    1772.000000    1.000000   3.190000
50%    1846.000000    2.000000   3.380000
75%    1934.000000    3.000000   3.502500
max    2050.000000    3.000000   3.810000

In [5]:
x = data[['SAT','Rand 1,2,3']]
y = data['GPA']

In [6]:
reg = LinearRegression()

In [7]:
reg.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [8]:
reg.score(x,y)

0.40668119528142815

In [9]:
reg.coef_

array([ 0.00165354, -0.00826982])

In [10]:
reg.intercept_

0.29603261264909353

In [11]:
x.shape

(84, 2)

In [12]:
x

SAT  Rand 1,2,3
0   1714           1
1   1664           3
2   1760           3
3   1685           3
4   1693           2
..   ...         ...
79  1936           3
80  1810           1
81  1987           3
82  1962           1
83  2050           2

[84 rows x 2 columns]

In [13]:
r2 = reg.score(x,y)

In [14]:
n = x.shape[0]

In [15]:
p = x.shape[1]

In [16]:
adjusted_r2 = 1-(1-r2) * (n-1)/(n-p-1)

In [17]:
adjusted_r2

0.39203134825134

In [18]:
from sklearn.feature_selection import f_regression

In [19]:
f_regression(x,y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [20]:
p_values = f_regression(x,y)[1]

In [21]:
p_values

array([7.19951844e-11, 6.76291372e-01])

In [22]:
p_values.round(3)

array([0.   , 0.676])

In [23]:
# Multiple regression with real estate dataset

In [24]:
data = pd.read_csv('real_estate_price_size_year.csv')

In [25]:
data.head()

price     size  year
0  234314.144   643.09  2015
1  228581.528   656.22  2009
2  281626.336   487.29  2018
3  401255.608  1504.75  2015
4  458674.256  1275.46  2009

In [26]:
x = data[['size','year']]
y = data['price']

In [27]:
reg = LinearRegression()
reg.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [28]:
reg.intercept_

-5772267.017463278

In [29]:
reg.score(x,y)

0.7764803683276796

In [30]:
reg.coef_

array([ 227.70085401, 2916.78532684])

In [31]:
def adj_r2 (x,y):
    r2 = reg.score(x,y)
    n = x.shape[0]
    p = 2
    adjusted_r2 = 1 - (1-r2) *( n - 1)/(n-p-1)
    return adjusted_r2

In [32]:
adj_r2(x,y)

0.7718717161282503

In [33]:
reg.predict([[750, 2009]])

array([258330.34465995])

In [34]:
f_regression(x,y)

(array([285.92105192,   0.85525799]), array([8.12763222e-31, 3.57340758e-01]))

In [35]:
p_values = f_regression(x,y)[1]

In [36]:
p_values.round(3)

array([0.   , 0.357])

In [37]:
# Scaling


data = pd.read_csv('1.02. Multiple linear regression.csv')
data.head()

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

In [38]:
data.shape

(84, 3)

In [39]:
x = data[['SAT','Rand 1,2,3']]
y = data['GPA']

In [40]:
from sklearn.preprocessing import StandardScaler

In [41]:
scaler = StandardScaler()

In [42]:
scaler.fit(x)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [43]:
x_scaled = scaler.transform(x)

In [44]:
x_scaled

array([[-1.26338288, -1.24637147],
       [-1.74458431,  1.10632974],
       [-0.82067757,  1.10632974],
       [-1.54247971,  1.10632974],
       [-1.46548748, -0.07002087],
       [-1.68684014, -1.24637147],
       [-0.78218146, -0.07002087],
       [-0.78218146, -1.24637147],
       [-0.51270866, -0.07002087],
       [ 0.04548499,  1.10632974],
       [-1.06127829,  1.10632974],
       [-0.67631715, -0.07002087],
       [-1.06127829, -1.24637147],
       [-1.28263094,  1.10632974],
       [-0.6955652 , -0.07002087],
       [ 0.25721362, -0.07002087],
       [-0.86879772,  1.10632974],
       [-1.64834403, -0.07002087],
       [-0.03150724,  1.10632974],
       [-0.57045283,  1.10632974],
       [-0.81105355,  1.10632974],
       [-1.18639066,  1.10632974],
       [-1.75420834,  1.10632974],
       [-1.52323165, -1.24637147],
       [ 1.23886453, -1.24637147],
       [-0.18549169, -1.24637147],
       [-0.5608288 , -1.24637147],
       [-0.23361183,  1.10632974],
       [ 1.68156984,

In [45]:
x_scaled.shape

(84, 2)

In [46]:
reg = LinearRegression()

In [47]:
reg.fit(x_scaled, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [48]:
reg.coef_

array([ 0.17181389, -0.00703007])

In [49]:
reg.intercept_

3.330238095238095

In [50]:
reg_summary = pd.DataFrame([['Bias'],['SAT'],['Rand 1,2,3']],columns = ['Features'])

In [52]:
reg_summary['Weights'] = reg.intercept_, reg.coef_[0], reg.coef_[1]

In [53]:
reg_summary

Features   Weights
0        Bias  3.330238
1         SAT  0.171814
2  Rand 1,2,3 -0.007030

In [55]:
new_data = pd.DataFrame(data = [[1700,2],[1800,1]], columns = ['SAT','Rand 1,2,3'])
new_data

SAT  Rand 1,2,3
0  1700           2
1  1800           1

In [56]:
reg.predict(new_data)

array([295.39979563, 312.58821497])

In [58]:
new_data_scaled = scaler.transform(new_data)

In [59]:
new_data_scaled

array([[-1.39811928, -0.07002087],
       [-0.43571643, -1.24637147]])

In [61]:
reg.predict(new_data_scaled)

array([3.09051403, 3.26413803])

In [62]:
reg_simple = LinearRegression()

In [63]:
x_simple_matrix = x_scaled[:, 0].reshape(-1,1)

In [65]:
reg_simple.fit(x_simple_matrix, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [71]:
reg_simple.predict(new_data_scaled[:,0].reshape(-1,1)).round(3)

array([3.09 , 3.255])