In [1]:
import numpy as np

In [2]:
np.random.seed(123)
matrix = np.random.randint(1,11,9).reshape(3,3)

In [3]:
matrix

array([[ 3,  3,  7],
       [ 2,  4, 10],
       [ 7,  2,  1]])

In [4]:
np.sum(matrix)

39

In [6]:
matrix.sum()

39

In [7]:
np.min(matrix)

1

In [8]:
np.max(matrix)

10

In [9]:
# rows = 1, columns = 0

In [10]:
matrix

array([[ 3,  3,  7],
       [ 2,  4, 10],
       [ 7,  2,  1]])

In [12]:
np.min(matrix, axis = 1)

array([3, 2, 1])

In [13]:
np.max(matrix, axis = 0)

array([ 7,  4, 10])

In [14]:
np.sum(matrix, axis = 1)

array([13, 16, 10])

In [15]:
np.cumsum(matrix)

array([ 3,  6, 13, 15, 19, 29, 36, 38, 39], dtype=int32)

In [17]:
np.cumsum(matrix, axis = 1)

array([[ 3,  6, 13],
       [ 2,  6, 16],
       [ 7,  9, 10]], dtype=int32)

In [20]:
np.prod(matrix, axis = 1)

array([63, 80, 14])