### Import numpy library  

In [1]:
import numpy as np

### Create an Array using array function  

In [2]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

### Create an Array containing numbers from 20 to 40 

In [5]:
arr2 = np.arange(20,41)
arr2

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40])

### Create an array which contain 10 elements and every element is 5  

In [22]:
arr3 = np.ones(10) * 5
arr3

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

### create a 1-d array and then convert it into 3-d array  

In [8]:
arr4 = np.random.randint(1,51,20)
arr4

array([12, 42, 40, 18, 21,  5, 34, 31, 43, 34, 30, 10, 29, 32,  1, 36, 41,
       49, 18, 32])

In [9]:
arr4.reshape(2,5,2)

array([[[12, 42],
        [40, 18],
        [21,  5],
        [34, 31],
        [43, 34]],

       [[30, 10],
        [29, 32],
        [ 1, 36],
        [41, 49],
        [18, 32]]])

### Create 2-d array which contains random 25 numbers between 0 and 1 

In [24]:
arr5 = np.random.rand(4,5)
arr5

array([[0.23264834, 0.21992066, 0.75447884, 0.05603487, 0.32136325],
       [0.99792479, 0.6070315 , 0.71341959, 0.50941864, 0.30603034],
       [0.60190412, 0.68656244, 0.76768162, 0.74258774, 0.06016782],
       [0.38851519, 0.26239898, 0.9617658 , 0.87914161, 0.64238066]])

### create array containing 20 random integer then replace every even number with -1 
#### Example - 
####                  array --- >  [44,55,12,6,3] 
####                  ouput ----> [-1,55, -1,-1,3]


In [29]:
arr6 = np.random.randint(1,50,20)
arr6[arr6%2 == 0] = -1
arr6

array([-1, 19, -1, -1, 41, 35, 33, -1, -1, -1, 19, -1, -1, 49, 27,  7, 29,
       -1, -1, 23])

#### You have a matrix 
[[5 , 10, 15, 20, 25],
[30, 35, 40, 45, 50],
[55, 60, 65, 70, 75],
[80, 85, 90, 95, 100]]

Extract
[30,35,40]
[55, 60, 65]

In [36]:
matrix = np.array([[5 , 10, 15, 20, 25],
                   [30, 35, 40, 45, 50],
                   [55, 60, 65, 70, 75],
                   [80, 85, 90, 95, 100]])
matrix[1:3,0:3]

array([[30, 35, 40],
       [55, 60, 65]])

### Concatenate two 1-d array   

In [45]:
arr7 = np.array([1,2,3])
arr8 = np.array([4,5,6])
np.hstack((arr7, arr8))

array([1, 2, 3, 4, 5, 6])

### Stack 2-d matrix horizontally and vertically

In [49]:
matrix2 = np.random.randint(1,10,9).reshape(3,3)
matrix3 = np.random.randint(1,20,9).reshape(3,3)
np.hstack((matrix2, matrix3))

array([[ 3,  1,  9, 14, 19, 17],
       [ 8,  6,  2,  6,  6,  3],
       [ 6,  4,  8, 13, 12, 16]])

In [50]:
np.vstack((matrix2, matrix3))

array([[ 3,  1,  9],
       [ 8,  6,  2],
       [ 6,  4,  8],
       [14, 19, 17],
       [ 6,  6,  3],
       [13, 12, 16]])